# pnpm 11+ reads pnpm settings from this file.
# https://pnpm.io/settings
packages:
  - server
  - web
allowBuilds:
  esbuild: true
  protobufjs: true
minimumReleaseAgeExclude:
  - '@univerjs/core@1.0.4'
  - '@univerjs/design@1.0.4'
  - '@univerjs/docs-ui@1.0.4'
  - '@univerjs/docs@1.0.4'
  - '@univerjs/drawing@1.0.4'
  - '@univerjs/engine-formula@1.0.4'
  - '@univerjs/engine-render@1.0.4'
  - '@univerjs/network@1.0.4'
  - '@univerjs/preset-sheets-core@1.0.4'
  - '@univerjs/presets@1.0.4'
  - '@univerjs/protocol@1.0.4'
  - '@univerjs/rpc@1.0.4'
  - '@univerjs/sheets-formula-ui@1.0.4'
  - '@univerjs/sheets-formula@1.0.4'
  - '@univerjs/sheets-numfmt-ui@1.0.4'
  - '@univerjs/sheets-numfmt@1.0.4'
  - '@univerjs/sheets-ui@1.0.4'
  - '@univerjs/sheets@1.0.4'
  - '@univerjs/telemetry@1.0.4'
  - '@univerjs/themes@1.0.4'
  - '@univerjs/ui@1.0.4'
overrides:
  '@grpc/grpc-js': 1.14.5
